apiVersion: apps/v1
kind: Deployment
metadata:
  name: motd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: motd
  template:
    metadata:
      labels:
        app: motd
    spec:
      containers:
      - name: motd-container
        image: amadouth/motd-api:latest # Image que vous voulez déployer
        ports:
        - containerPort: 80
